name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: danielga/garrysmod_common
          ref: master
          path: garrysmod_common
          submodules: recursive

      - name: Install deps
        run: |
          # Было: v5.0.0-beta2
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta7/premake-5.0.0-beta7-linux.tar.gz -O premake.tar.gz
          tar -xvf premake.tar.gz
          chmod +x premake5
          sudo cp premake5 /usr/bin
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential cmake gdb git wget g++ g++-multilib gcc-multilib libc6-dev-i386
          premake5 --version


      - name: Generate Project
        run: premake5 --gmcommon=garrysmod_common gmake

      - name: Make
        run: |
          cd projects/linux/gmake
          make -j"$(nproc)"
          make config=release_x86 -j"$(nproc)"
          ls

      - name: Upload Linux Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux_build_artifacts
          path: |
            projects/linux/gmake/**/x86/**
            projects/linux/gmake/**/x86_64/**
